# run: conda env create --file environment.yml
name: unet-env-test
channels:
- defaults
- conda-forge
dependencies:
#- ddt
#- markdown
#- pandas
#- pillow
- pip
- python==3.8.10 # for sphinx to work 3.6.13
#- pytorch
#- tensorboard
#- yaml
- pip:
  - furo==2022.9.29
  - myst_parser
  #- ray
  - sphinx==4.0 # for furo to work
  - sphinx-togglebutton